### ISSUE TITLE
CW Navbar

### ISSUE THREAD

**Issue by Sithumya99** [MrJavaScripty/web-development#1]
I'm in-charge of making the navbar for the cw website in my team and I was wondering if there's any way to apply the navbar to every page without having to copy paste the code.

I looked it up and found 2 methods that use javascript, but I can't figure out how to make either work.

[1st method ](https://stackoverflow.com/questions/31954089/how-can-i-reuse-a-navigation-bar-on-multiple-pages) - 

        keep the navbar html code in nav.html file and include the below code in nav.js
        
        fetch('nav.html')
        .then(res => res.text())
        .then(text => {
            let oldelem = document.querySelector("script#replace_with_navbar");
            let newelem = document.createElement("div");
            newelem.innerHTML = text;
            oldelem.parentNode.replaceChild(newelem,oldelem);
        })
        
        And include this line in the other html files:
        <script id="replace_with_navbar" src="nav.js"></script>

I tried this one but it didn't work, the console says - Uncaught ReferenceError: res is not defined and I don't know how to debug that.

[2nd method](https://www.w3schools.com/howto/howto_html_include.asp) - 

I don't understand the code in this one so I haven't tried it yet.

Every other way I could find to do it was by using either php or jquery.

**Comment by MrJavaScripty** [comment]
Unfortunately this isn't very easy. It's the whole reason JavaScript Frameworks are taking over. 

One really nice alternative is something called Web Components. It's not easy by any means but extremely useful. It allows you to create custom components HTML components, but at the cost of a lot of configuration. This allows you to configure certain logic via JS and sort of remove some of that rewriting you have to do across all HTML pages. They're well supported so give it a look. 

Only other alternative aside from this are HTML Templating libraries alongside server side tools like PHP, Node etc. I don't recommend this at this stage simply due to the level of complexity. You might be able to figure it out but you have to think of your team members as well. 

So my suggestion right now would be to
A - Learn Web Components

Or

B - Stick with basic HTML and simply copy and paste (it's ugly but it works)

**Comment by MrJavaScripty** [comment]
@Sithumya99 as per the `ReferenceError` in your code, I need to see your `nav.html`, the script tag and the script itself to see where the problem is. Just based off the snippet it should work but I can't say for sure it isn't a mistake that you've caused.

**Comment by Sithumya99** [comment]
Ahh ok I'll try out the web components and see if I can make it work

**Comment by Sithumya99** [comment]
I can email you my code if that's ok?

**Comment by Sithumya99** [comment]
I sent you an email with the html and js code.
